### ISSUE TITLE
I'm looking for a RPLidar java lib - why is yours DEPRICATED?

### ISSUE THREAD

**Issue by rlsutton1** [ev3dev-lang-java/RPLidar4J#2]
I'm currently looking for a java lib for an RPLidar.

I'm wondering why you've marked your lib as DEPRICATED? 

Is there some fundamental problem that can't be solved or is there a better lib to use that I'm unaware of?

Thanks.

**Comment by jabrena** [comment]
Hi,

because I unified this development with other USB sensors in this library:
https://github.com/ev3dev-lang-java/usb-devices/tree/develop

Juan Antonio
