### ISSUE TITLE
How to "Add the dependency on the project"

### ISSUE THREAD

**Issue by YuHanChen04** [ev3dev-lang-java/RPLidar4J#4]
Hello , I want to do it ,but I don't know how can I do.
Could you give some suggestion , let me can success to do .

Thank you so much !

Sorry fo my English

**Comment by jabrena** [comment]
Hi @YuHanChen04,

did you test this repo:
https://github.com/ev3dev-lang-java/usb-devices/tree/develop/src/test/java/examples

It has multiple examples.

This repo was deprecated and the evolution of the RPLIDAR support is stored there.

Tell me if you have some issue.

Note: For future issues, use this repo:
https://github.com/ev3dev-lang-java/ev3dev-lang-java/issues

Cheers

Juan Antonio

**Comment by YuHanChen04** [comment]
HI @jabrena Thank you so much for your anwser
I had installed ev3dev-lang-java(LeJos) on my ev3 brickman with ev3dev OS.
If i compile your script will it can be successful ?
device : RPLidar A2 .

**Comment by jabrena** [comment]
Yes, but you will have to install the native library rxtxjava for serial comms.
 apt-get install --yes --no-install-recommends librxtx-java

**Comment by jabrena** [comment]
What EV3Dev version are you using?
Platform? EV3 Brick?

**Comment by YuHanChen04** [comment]
I already install the native library rxtxjava !! 
My ev3dev verison is ver new 4.4.87-22-ev3dev-ev3 !!
Yes I use ev3 Brick !


Thanks so much
Sorry for my English

**Comment by jabrena** [comment]
``` groovy
task remoteRun << {
    ssh.run {
        session(remotes.ev3dev) {
            println "java -Djava.library.path=/usr/lib/jni/ -server -jar /home/robot/" + "${rootProject.name}" + "-all-" + version + ".jar "
            execute "java -Djava.library.path=/usr/lib/jni/ -server -jar /home/robot/" + "${rootProject.name}" + "-all-" + version + ".jar "
        }
    }
}
```

**Comment by jabrena** [comment]
Take a look a way to run your jar in order to run your example

**Comment by YuHanChen04** [comment]
Hi  @jabrena :
I am successful on the repo of "installer" and run the script of "MyFirstRobot",
and I try to run the usb-device is also failed !

**Comment by jabrena** [comment]
Hi @YuHanChen04,

If I understand your comment, you run the example from the template but why you have a problem with usb-device?

Can you explain the problem?
Can put the traces with the error?

Juan Antonio

**Comment by YuHanChen04** [comment]
Hi @jabrena 
I want to say that I try  the repo of "installer" and "template " was successful.
And try "usb-device" is failed 
I really sorry to let you feel confused. > ///< 
Sorry for my English.

**Comment by jabrena** [comment]
Hi @YuHanChen04,

Can you explain the problem with usb-device in detail?

Can you paste the error traces?

Juan Antonio

**Comment by YuHanChen04** [comment]
It is I run the usb-device 


```
Yu-Hande-MacBook-Pro-2:usb-devices Yu-Han$ ./gradlew deployAndRun

> Task :compileJava 
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

> Task :deploy 
Strict host key checking is off. It may be vulnerable to man-in-the-middle attacks.

> Task :remoteRun 
Strict host key checking is off. It may be vulnerable to man-in-the-middle attacks.
java -Djava.library.path=/usr/lib/jni/ -server -jar /home/robot/usb-devices-all-0.2.0-SNAPSHOT.jar 

ev3dev#12|Error: Main method not found in class ev3dev.sensors.slamtec.service.RpLidarScan, please define the main method as:
ev3dev#12|   public static void main(String[] args)
ev3dev#12|or a JavaFX application class must extend javafx.application.Application

> Task :remoteRun FAILED
Failed command ev3dev#12 with status 1: java -Djava.library.path=/usr/lib/jni/ -server -jar /home/robot/usb-devices-all-0.2.0-SNAPSHOT.jar 


FAILURE: Build failed with an exception.

* Where:
Script '/Users/Yu-Han/IdeaProjects/ev3java/usb-devices/deploy.gradle' line: 27

* What went wrong:
Execution failed for task ':remoteRun'.
> Command returned exit status 1: java -Djava.library.path=/usr/lib/jni/ -server -jar /home/robot/usb-devices-all-0.2.0-SNAPSHOT.jar 

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
See https://docs.gradle.org/4.6/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 24s
6 actionable tasks: 6 executed
Yu-Hande-MacBook-Pro-2:usb-devices Yu-Han$ 

```

**Comment by YuHanChen04** [comment]
I use IntelliJ IEDA 
And I also have modify the "MANIFEST.MF"
My ev3 brick also git the repo.
I don't how to do .....

Sorry for my English
Hope that you can understand what I mean.

**Comment by jabrena** [comment]
Hi,

Can you paste the content of MANIFEST.MF?

```
ev3dev#12|Error: Main method not found in class ev3dev.sensors.slamtec.service.RpLidarScan, please define the main method as:
ev3dev#12|   public static void main(String[] args)
ev3dev#12|or a JavaFX application class must extend javafx.application.Application
```

Maybe, you are indicating in the MANIFEST.MF to run the class RpLidarScan

Do you have the project in some repo?

Juan Antonio

**Comment by jabrena** [comment]
Did you solve the problem @YuHanChen04 ?

**Comment by YuHanChen04** [comment]
Hi , @jabrena 
NO , I didn't.
I think I don't have talent >"<

I think I need re-explain the steps.
1. I git clone the repo of "installer" to my PC  :
 install , "./gradlew testConnection" , and deploy new class of "MyFirstRobot.java" , all succeeded.

2. git clone "usb-device" in  pc and brick ,  succeeded "/gradlew testConnection" , 
and the MANIFEST.MF  : 
`Manifest-Version: 1.0
Implementation-Title: EV3Dev-lang-java / usb-devices
Implementation-Version: 0.2.0-SNAPSHOT
Implementation-Vendor: Juan Antonio Breña Moral
Main-Class: ev3dev.sensors.slamtec.model.scan`


Command "./gradlew deployAndRun" on terminal :
```
Yu-Hande-MacBook-Pro-2:usb-devices Yu-Han$ ./gradlew deployAndRun

> Task :compileJava 
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

> Task :deploy 
Strict host key checking is off. It may be vulnerable to man-in-the-middle attacks.

> Task :remoteRun 
Strict host key checking is off. It may be vulnerable to man-in-the-middle attacks.
java -Djava.library.path=/usr/lib/jni/ -server -jar /home/robot/usb-devices-all-0.2.0-SNAPSHOT.jar 

ev3dev#2|Error: Could not find or load main class ev3dev.sensors.slamtec.model.scan

> Task :remoteRun FAILED
Failed command ev3dev#2 with status 1: java -Djava.library.path=/usr/lib/jni/ -server -jar /home/robot/usb-devices-all-0.2.0-SNAPSHOT.jar 


FAILURE: Build failed with an exception.

* Where:
Script '/Users/Yu-Han/IdeaProjects/ev3java/usb-devices/deploy.gradle' line: 27

* What went wrong:
Execution failed for task ':remoteRun'.
> Command returned exit status 1: java -Djava.library.path=/usr/lib/jni/ -server -jar /home/robot/usb-devices-all-0.2.0-SNAPSHOT.jar 

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
See https://docs.gradle.org/4.6/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 29s
6 actionable tasks: 6 executed
```



Thank for you
Sorry fo my English ......

**Comment by YuHanChen04** [comment]
sorry ,I accidentally this issues  ><

**Comment by jabrena** [comment]
Hi @YuHanChen04,

I read the steps that you followed and maybe you skipped a step:

1.1 Add a dependency in your Template project.

Using the template project, you executed the Example:  `MyFirstRobot.java`

> I git clone the repo of "installer" to my PC :
> install , "./gradlew testConnection" , and deploy new class of "MyFirstRobot.java" , all succeeded.

But later, you cloned the library about usb and this is the mistake. In the same project add the dependency here: `build.gradle` in the area about dependecies:

https://github.com/ev3dev-lang-java/template_project_gradle/blob/master/build.gradle

```
dependencies {
    compile("ch.qos.logback:logback-classic:1.2.3")
    compile("com.github.ev3dev-lang-java:ev3dev-lang-java:0.7.0")
}
```

To know how to add a dependency, go to the mvn repository to get the way to add the library in your project:

https://jitpack.io/#ev3dev-lang-java/usb-devices/0.2.0

So, update your project with this line:

```
dependencies {
    compile("ch.qos.logback:logback-classic:1.2.3")
    compile("com.github.ev3dev-lang-java:ev3dev-lang-java:0.7.0")
    compile("com.github.ev3dev-lang-java:usb-devices:0.2.0")
}
```

And add one example for the LIDAR in the package examples:

```
package example;

import ev3dev.sensors.slamtec.RPLidarA1;
import ev3dev.sensors.slamtec.RPLidarA1ServiceException;
import ev3dev.sensors.slamtec.RPLidarProviderListener;
import ev3dev.sensors.slamtec.model.Scan;
import ev3dev.sensors.slamtec.model.ScanDistance;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.concurrent.atomic.AtomicInteger;

public class Demo6 {

   public static Logger log = LoggerFactory.getLogger(ButtonExample.class);

    private static AtomicInteger counter;
    private static volatile int samplesPerSecond;

    public static void main(String[] args) throws Exception {

        log.info("Testing RPLidar on a EV3Dev with Java");

        final String USBPort = "/dev/ttyUSB0";
        final RPLidarA1 lidar = new RPLidarA1(USBPort);
        lidar.init();

        Runtime.getRuntime().addShutdownHook(new Thread(new Runnable() {
            public void run() {
                System.out.println("Close Lidar");
                try {
                    lidar.close();
                } catch (RPLidarA1ServiceException e) {
                    e.printStackTrace();
                }
            }
        }));

        lidar.addListener(new RPLidarProviderListener() {
            @Override
            public void scanFinished(final Scan scan) {
                final int counter = scan.getDistances().size();

                for (ScanDistance scanDistance: scan.getDistances()) {
                    log.info("Angle: {}, Distance: {}, Quality: {}", scanDistance.getAngle(), scanDistance.getDistance(), scanDistance.getQuality());
                }

                synchronized (this) {
                    samplesPerSecond += counter;
                }
            }
        });

        int counter = 0;

        boolean flag = true;
        while(flag){

            lidar.scan();

            counter++;
            log.info("Counter: {}, Samples: ;{}", counter, samplesPerSecond);
            samplesPerSecond = 0;

            if(counter > 5){
                break;
            }
        }

        lidar.close();
        log.info("End");
        System.exit(0);
    }

}
```

and update MANIFEST.MF from template project to run the right example:

```
Manifest-Version: 1.0
Implementation-Title: EV3Dev-lang-java // Template project
Implementation-Version: 0.3.0
Implementation-Vendor: Juan Antonio Breña Moral
Main-Class: example.Demo6
```

I hope that the explanation solve your doubt. We develop libraries to put all together, fix that concept.

Cheers

Juan Antonio

**Comment by YuHanChen04** [comment]
Hi @jabrena thank you very very very much !!

I try the step you told , it seem to success

But I command `./gradlew deployAndRun`
and it responds :
```
> Task :compileJava 
/Users/Yu-Han/IdeaProjects/ev3java/template_project_gradle/src/main/java/example/Demo6.java:15: error: cannot find symbol
    public static Logger log = LoggerFactory.getLogger(ButtonExample.class);
                                                       ^
  symbol:   class ButtonExample
  location: class Demo6
1 error


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
See https://docs.gradle.org/4.6/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 3s
2 actionable tasks: 1 executed, 1 up-to-date
```

I think if I change the repo of "example" , will success ?

**Comment by jabrena** [comment]
Hi,

sorry, I added the line from other example:

```
public class Demo6 {

   public static Logger log = LoggerFactory.getLogger(Demo6.class);
```

Test now.

**Comment by YuHanChen04** [comment]
Hi ,
Thank so much !!

but it already success
!!!


```
Yu-Hande-MacBook-Pro-2:template_project_gradle Yu-Han$ ./gradlew deployAndRun

> Task :deploy 
Strict host key checking is off. It may be vulnerable to man-in-the-middle attacks.


FAILURE: Build failed with an exception.

* Where:
Script '/Users/Yu-Han/IdeaProjects/ev3java/template_project_gradle/gradle/deploy.gradle' line: 15

* What went wrong:
Execution failed for task ':deploy'.
> com.jcraft.jsch.JSchException: timeout: socket is not established

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
See https://docs.gradle.org/4.6/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 1m 2s
5 actionable tasks: 5 executed

```

**Comment by jabrena** [comment]
In what kind of project are you thinking to do with the LIDAR and the EV3 Brick?

**Comment by YuHanChen04** [comment]
Thank for you 
I want to use EV3 brick with RPLIDAR to measure the data of surrounding environment

**Comment by jabrena** [comment]
Do you have a repo to store the whole project?
Did you think in ROS?

**Comment by jabrena** [comment]
Using ROS and RVIZ, it is possible to measure the environment.
Take a look this example:

![](https://scontent-cdt1-1.xx.fbcdn.net/v/t1.0-9/21761544_10154979418973527_4344428421110253478_n.jpg?_nc_cat=0&_nc_eui2=v1%3AAeEPjHfTqx_qLOnCwGUANQcKk3rrBVQOAbBPumYx3jjEnkBVwR7dZAHPhTRJsw6lUeT40yV5-yRMJV7FjG1iLtTibRyx8SzJEx_ovj82OBpl-g&oh=7d096f9f0832e41f9c1c6ddf9611a961&oe=5B97485F)

This is a screenshot between the integration of EV3 and RPLIDAR with ROS

**Comment by jabrena** [comment]
https://www.youtube.com/watch?v=pCF7P7u8pDk

**Comment by YuHanChen04** [comment]
Thank for you@jabrena 

 I think the best way to combine EV3 brick and LIDAR is ROS !
But I am  very interested in  ev3dev. 
So I read your repo and test it ,hope it  will be successful
 
Sorry for my ENGLISH .

**Comment by jabrena** [comment]
If you like, we could research how to create Maps with some `ROS` Utilities and `EV3 Brick` an `RPLIDAR`.
If you like we could do together.

**Comment by YuHanChen04** [comment]
Hi @jabrena 
Yes ,maybe we can do it.

But it seem to a good news !!!!!
I test it again today , I got the response!
Maybe you could give solution to me 



```
> Task :remoteRun FAILED
Failed command ev3dev#3 with status 1: java -server -jar /home/robot/template_project_gradle-all-0.4.0.jar 


FAILURE: Build failed with an exception.

* Where:
Script '/Users/Yu-Han/IdeaProjects/ev3java/template_project_gradle/gradle/deploy.gradle' line: 27

* What went wrong:
Execution failed for task ':remoteRun'.
> Command returned exit status 1: java -server -jar /home/robot/template_project_gradle-all-0.4.0.jar 

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
See https://docs.gradle.org/4.6/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 55s
6 actionable tasks: 5 executed, 1 up-to-date


```

Thanks so mush again!

**Comment by jabrena** [comment]
Hi @YuHanChen04,

You have to find the differences... :p 

**KO Execution:**
> Command returned exit status 1: java -server -jar /home/robot/template_project_gradle-all-0.4.0.jar 

**OK Execution:**
> Command returned exit status 1: java -Djava.library.path=/usr/lib/jni/ -server -jar /home/robot/usb-devices-all-0.2.0-SNAPSHOT.jar 

The usage of RPLIDAR devices requires RXTX for Java, so we have to use some native features.

You have 2 alternatives:

Upgrade deploy.gradle to send the parameter: `-Djava.library.path=/usr/lib/jni/` or open a remote connection and deploy the jar and later from the terminal call:

```
java -Djava.library.path=/usr/lib/jni/ -jar /home/robot/template_project_gradle-all-0.4.0.jar 
```

Cheers

Juan Antonio

**Comment by YuHanChen04** [comment]
HI @jabrena 
I test 2nd alternative was successful.
And I want to test  the first alternative , I am also confused!
So what can I do  to upgrade the deploy.gradle file ! 

Thanks 
YuHanChen

**Comment by jabrena** [comment]
Tinker a bit with `deploy.gradle`... :)

**Comment by YuHanChen04** [comment]
Hello  , @jabrena :

I test successful !
It can scan and I get some data !
I fell so excited !
Thank so much 
I think you are a very nice !

**Comment by jabrena** [comment]
Think in the idea about `ROS`, we could research together.

The best tools with `RPLIDAR` are designed for `ROS`. ;)

**Comment by YuHanChen04** [comment]
Alright , we can keep going on the **ROS**. @jabrena 
But now , I need to know what is the **ROS**
'cause I didn't use that.
Hope that you will help me to do .

Thanks so much , sorry for my English.

**Comment by jabrena** [comment]
Hi mate,

if you like, I am going to close this issue, because we solved your doubt.
In relation to ROS matter, can you create a new issue here:
https://github.com/ev3dev-lang-java/ev3dev-lang-java/issues

Cheers

Juan Antonio
